-- Consolidated admin/access update script
-- Built from the current workspace SQL files and aligned with the latest
-- Supabase backup dated 2026-05-25.

begin;

-- ---------------------------------------------------------------------------
-- 1) Pending registration OTP support
-- ---------------------------------------------------------------------------

create extension if not exists pg_cron;

alter table public.users
add column if not exists otp text,
add column if not exists otp_created_at timestamptz;

create or replace function public.expire_otps()
returns void
language sql
security definer
as $func$
  update public.users
  set otp = 'Expired'
  where otp is not null
    and otp <> 'Expired'
    and otp_created_at is not null
    and otp_created_at <= now() - interval '60 seconds';
$func$;

do $do$
begin
  if exists (
    select 1
    from cron.job
    where jobname = 'expire-user-otp'
  ) then
    perform cron.unschedule('expire-user-otp');
  end if;

  perform cron.schedule(
    'expire-user-otp',
    '* * * * *',
    'select public.expire_otps();'
  );
exception
  when undefined_table or insufficient_privilege then
    raise notice 'pg_cron metadata is not available or insufficient privilege; skipping cron schedule';
end
$do$;

do $do$
begin
  if exists (
    select 1
    from pg_tables
    where schemaname = 'public'
      and tablename = 'users'
  ) then
    alter table public.users enable row level security;
  end if;
end
$do$;

do $do$
begin
  if exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'users'
      and policyname = 'public_can_create_pending_registration'
  ) then
    drop policy public_can_create_pending_registration on public.users;
  end if;

  if exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'users'
      and policyname = 'public_can_update_pending_registration'
  ) then
    drop policy public_can_update_pending_registration on public.users;
  end if;

  if exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'users'
      and policyname = 'public_can_read_pending_registration'
  ) then
    drop policy public_can_read_pending_registration on public.users;
  end if;

  if exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'users'
      and policyname = 'public_can_delete_expired_pending_registration'
  ) then
    drop policy public_can_delete_expired_pending_registration on public.users;
  end if;

  if exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'users'
      and policyname = 'public_can_insert_otp'
  ) then
    drop policy public_can_insert_otp on public.users;
  end if;

  if exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'users'
      and policyname = 'public_can_update_otp'
  ) then
    drop policy public_can_update_otp on public.users;
  end if;

  if exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'users'
      and policyname = 'public_can_read_otp'
  ) then
    drop policy public_can_read_otp on public.users;
  end if;

  create policy public_can_insert_otp
  on public.users
  for insert
  to anon, authenticated
  with check (true);

  create policy public_can_update_otp
  on public.users
  for update
  to anon, authenticated
  using (true)
  with check (true);

  create policy public_can_read_otp
  on public.users
  for select
  to anon, authenticated
  using (true);
end
$do$;

-- ---------------------------------------------------------------------------
-- 2) User role power override support
-- ---------------------------------------------------------------------------

alter table public.users
add column if not exists removed_role_powers jsonb not null default '[]'::jsonb;

alter table public.users
drop constraint if exists users_removed_role_powers_array_check;

alter table public.users
add constraint users_removed_role_powers_array_check
check (jsonb_typeof(removed_role_powers) = 'array');

-- ---------------------------------------------------------------------------
-- 3) Access request workflow tables
-- ---------------------------------------------------------------------------

create table if not exists public.access_requests (
    id bigint generated by default as identity primary key,
    user_id text not null references public.users(id) on update cascade on delete cascade,
    user_name text,
    user_email text,
    current_role_name text,
    requested_role_name text not null,
    requested_power_keys jsonb not null default '[]'::jsonb,
    status text not null default 'pending' check (status in ('pending', 'approved', 'denied', 'cancelled')),
    request_note text,
    reviewed_note text,
    requested_by text,
    reviewed_by text,
    reviewed_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint access_requests_requested_power_keys_array_check
        check (jsonb_typeof(requested_power_keys) = 'array')
);

create or replace function public.touch_access_request_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_touch_access_request_updated_at on public.access_requests;

create trigger trg_touch_access_request_updated_at
before update on public.access_requests
for each row
execute function public.touch_access_request_updated_at();

create index if not exists idx_access_requests_status
on public.access_requests (status);

create index if not exists idx_access_requests_user_id
on public.access_requests (user_id);

create index if not exists idx_access_requests_created_at
on public.access_requests (created_at desc);

create index if not exists idx_access_requests_requested_by
on public.access_requests (requested_by);

alter table public.access_requests enable row level security;

drop policy if exists access_requests_select_all on public.access_requests;
drop policy if exists access_requests_insert_all on public.access_requests;
drop policy if exists access_requests_update_all on public.access_requests;

create policy access_requests_select_all
on public.access_requests
for select
to anon, authenticated
using (true);

create policy access_requests_insert_all
on public.access_requests
for insert
to anon, authenticated
with check (true);

create policy access_requests_update_all
on public.access_requests
for update
to anon, authenticated
using (true)
with check (true);

grant all on table public.access_requests to anon, authenticated, service_role;
grant all on function public.touch_access_request_updated_at() to anon, authenticated, service_role;

do $do$
begin
  if exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'access_requests_id_seq'
      and c.relkind = 'S'
  ) then
    execute 'grant all on sequence public.access_requests_id_seq to anon, authenticated, service_role';
  end if;
end
$do$;

-- ---------------------------------------------------------------------------
-- 4) Access audit log
-- ---------------------------------------------------------------------------

create table if not exists public.access_audit_log (
    id bigint generated by default as identity primary key,
    target_user_id text not null references public.users(id) on update cascade on delete cascade,
    target_user_name text,
    target_user_email text,
    action_type text not null,
    previous_role text,
    new_role text,
    added_power_keys jsonb not null default '[]'::jsonb,
    removed_power_keys jsonb not null default '[]'::jsonb,
    final_power_keys jsonb not null default '[]'::jsonb,
    request_id bigint,
    performed_by text,
    performed_by_user_id text,
    note text,
    created_at timestamptz not null default now(),
    constraint access_audit_added_power_keys_array_check check (jsonb_typeof(added_power_keys) = 'array'),
    constraint access_audit_removed_power_keys_array_check check (jsonb_typeof(removed_power_keys) = 'array'),
    constraint access_audit_final_power_keys_array_check check (jsonb_typeof(final_power_keys) = 'array')
);

alter table public.access_audit_log
drop constraint if exists access_audit_log_action_type_check;

alter table public.access_audit_log
add constraint access_audit_log_action_type_check
check (
  action_type = any (
    array[
      'request_submitted'::text,
      'approved'::text,
      'denied'::text,
      'role_changed'::text,
      'powers_changed'::text,
      'promoted'::text,
      'powers_reset'::text
    ]
  )
);

create index if not exists idx_access_audit_target_user_id
on public.access_audit_log (target_user_id);

create index if not exists idx_access_audit_created_at
on public.access_audit_log (created_at desc);

create index if not exists idx_access_audit_request_id
on public.access_audit_log (request_id);

alter table public.access_audit_log enable row level security;

drop policy if exists access_audit_select_all on public.access_audit_log;
drop policy if exists access_audit_insert_all on public.access_audit_log;

create policy access_audit_select_all
on public.access_audit_log
for select
to anon, authenticated
using (true);

create policy access_audit_insert_all
on public.access_audit_log
for insert
to anon, authenticated
with check (true);

grant all on table public.access_audit_log to anon, authenticated, service_role;

do $do$
begin
  if exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'access_audit_log_id_seq'
      and c.relkind = 'S'
  ) then
    execute 'grant all on sequence public.access_audit_log_id_seq to anon, authenticated, service_role';
  end if;
end
$do$;

-- ---------------------------------------------------------------------------
-- 5) Base access/control powers
-- ---------------------------------------------------------------------------

insert into public.powers (key, code, description, created_at)
select 'Power036', 'req_power', 'Allows a user to submit access requests', now()
where not exists (
    select 1 from public.powers where lower(code) = 'req_power'
);

insert into public.powers (key, code, description, created_at)
select 'Power037', 'approve_or_deny_power', 'Allows reviewing and approving or denying access requests', now()
where not exists (
    select 1 from public.powers where lower(code) = 'approve_or_deny_power'
);

insert into public.powers (key, code, description, created_at)
select 'Power038', 'edit_roles_and_power', 'Allows direct editing of roles and additional powers', now()
where not exists (
    select 1 from public.powers where lower(code) = 'edit_roles_and_power'
);

insert into public.powers (key, code, description, created_at)
select 'Power039', 'approve_oe_deny_power', 'Legacy alias for approve_or_deny_power kept for backward compatibility', now()
where not exists (
    select 1 from public.powers where lower(code) = 'approve_oe_deny_power'
);

-- ---------------------------------------------------------------------------
-- 6) Power categories
-- ---------------------------------------------------------------------------

create table if not exists public.powers_category (
    name text primary key,
    description text,
    created_at timestamptz not null default now()
);

insert into public.powers_category (name, description)
select 'Access Control', 'Permissions related to access requests, approvals, and role control'
where not exists (
    select 1 from public.powers_category where lower(name) = 'access control'
);

insert into public.powers_category (name, description)
select 'General', 'Fallback category for uncategorized powers'
where not exists (
    select 1 from public.powers_category where lower(name) = 'general'
);

insert into public.powers_category (name, description)
select 'Messages', 'Permissions related to messages and replies'
where not exists (
    select 1 from public.powers_category where lower(name) = 'messages'
);

insert into public.powers_category (name, description)
select 'Orders And Sales', 'Permissions related to orders, sales, and dashboards'
where not exists (
    select 1 from public.powers_category where lower(name) = 'orders and sales'
);

insert into public.powers_category (name, description)
select 'Products', 'Permissions related to products and stock'
where not exists (
    select 1 from public.powers_category where lower(name) = 'products'
);

insert into public.powers_category (name, description)
select 'Site Management', 'Permissions related to site configuration and content'
where not exists (
    select 1 from public.powers_category where lower(name) = 'site management'
);

insert into public.powers_category (name, description)
select 'Users And Passwords', 'Permissions related to user creation, editing, and password management'
where not exists (
    select 1 from public.powers_category where lower(name) = 'users and passwords'
);

insert into public.powers_category (name, description)
select 'Wallet', 'Permissions related to wallet access and balance actions'
where not exists (
    select 1 from public.powers_category where lower(name) = 'wallet'
);

alter table public.powers
add column if not exists category text;

update public.powers
set category = case
    when lower(code) like 'product_%' then 'Products'
    when lower(code) like 'wallet_%' then 'Wallet'
    when lower(code) like 'message_%' then 'Messages'
    when lower(code) like 'user_%' or lower(code) like '%password%' then 'Users And Passwords'
    when lower(code) like 'order_%' or lower(code) like 'orders_%' or lower(code) like 'dashboard_%' or lower(code) = 'sales_dashboard' then 'Orders And Sales'
    when lower(code) like 'update_%' or lower(code) in ('site_control', 'about_edit', 'slider_manage', 'footer_manage', 'category_manage', 'loader_manage', 'site_logo_manage') then 'Site Management'
    when lower(code) like 'control_center_%' or lower(code) in ('master_control', 'master_controll', 'req_power', 'approve_or_deny_power', 'approve_oe_deny_power', 'edit_roles_and_power') then 'Access Control'
    else 'General'
end
where category is null or trim(category) = '';

insert into public.powers_category (name, description)
select distinct category, null
from public.powers
where category is not null
  and trim(category) <> ''
  and not exists (
      select 1
      from public.powers_category pc
      where lower(pc.name) = lower(public.powers.category)
  );

alter table public.powers
drop constraint if exists powers_category_fkey;

alter table public.powers
add constraint powers_category_fkey
foreign key (category)
references public.powers_category(name)
on update cascade
on delete set null;

alter table public.powers_category enable row level security;

drop policy if exists powers_category_select_all on public.powers_category;
drop policy if exists powers_category_insert_all on public.powers_category;
drop policy if exists powers_category_update_all on public.powers_category;

create policy powers_category_select_all
on public.powers_category
for select
to anon, authenticated
using (true);

create policy powers_category_insert_all
on public.powers_category
for insert
to anon, authenticated
with check (true);

create policy powers_category_update_all
on public.powers_category
for update
to anon, authenticated
using (true)
with check (true);

grant all on table public.powers_category to anon, authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 7) Standardized module view/edit powers and role backfill
-- ---------------------------------------------------------------------------

with next_key as (
    select coalesce(max((regexp_match(key, '([0-9]+)$'))[1]::int), 0) as max_key_num
    from public.powers
),
required_powers(code, description, category) as (
    values
        ('dashboard_edit', 'Edit dashboard-level operational controls', 'Orders And Sales'),
        ('order_view', 'View customer orders and order history', 'Orders And Sales'),
        ('order_edit', 'Edit order states and perform order actions', 'Orders And Sales'),
        ('message_edit', 'Reply to, update, and manage support messages', 'Messages'),
        ('wallet_edit', 'Adjust wallet balances and wallet-related actions', 'Wallet'),
        ('user_view', 'View user module access and user workflows', 'Users And Passwords'),
        ('update_view', 'View website update module access', 'Site Management'),
        ('update_edit', 'Edit website content, configuration, and site assets', 'Site Management'),
        ('control_center_view', 'View Control Center access workflows', 'Access Control'),
        ('control_center_edit', 'Edit roles, powers, and Control Center workflows', 'Access Control')
),
missing as (
    select rp.*
    from required_powers rp
    where not exists (
        select 1
        from public.powers p
        where lower(p.code) = lower(rp.code)
    )
),
numbered as (
    select
        row_number() over (order by code) as rn,
        code,
        description,
        category
    from missing
)
insert into public.powers (key, code, description, created_at, category)
select
    'Power' || lpad((next_key.max_key_num + numbered.rn)::text, 3, '0') as key,
    numbered.code,
    numbered.description,
    now(),
    numbered.category
from numbered
cross join next_key;

update public.powers
set category = case
    when lower(code) like 'product_%' then 'Products'
    when lower(code) like 'wallet_%' then 'Wallet'
    when lower(code) like 'message_%' then 'Messages'
    when lower(code) like 'user_%' or lower(code) like '%password%' then 'Users And Passwords'
    when lower(code) like 'order_%'
      or lower(code) like 'orders_%'
      or lower(code) like 'dashboard_%'
      or lower(code) = 'sales_dashboard' then 'Orders And Sales'
    when lower(code) like 'update_%'
      or lower(code) in ('site_control', 'about_edit', 'slider_manage', 'footer_manage', 'category_manage', 'loader_manage', 'site_logo_manage') then 'Site Management'
    when lower(code) like 'control_center_%'
      or lower(code) in ('master_control', 'master_controll', 'req_power', 'approve_or_deny_power', 'approve_oe_deny_power', 'edit_roles_and_power') then 'Access Control'
    else category
end;

update public.roles r
set role_powers = (
    select array(
        select distinct power_key
        from (
            select unnest(coalesce(r.role_powers, array[]::text[])) as power_key
            union all
            select 'dashboard_view'
            where exists (
                select 1
                from unnest(coalesce(r.role_powers, array[]::text[])) as legacy(power_key)
                where lower(legacy.power_key) in ('sales_dashboard', 'dashboard_edit')
            )
            union all
            select 'dashboard_edit'
            where exists (
                select 1
                from unnest(coalesce(r.role_powers, array[]::text[])) as legacy(power_key)
                where lower(legacy.power_key) = 'sales_dashboard'
            )
            union all
            select 'order_view'
            where exists (
                select 1
                from unnest(coalesce(r.role_powers, array[]::text[])) as legacy(power_key)
                where lower(legacy.power_key) in ('sales_dashboard', 'order_complete', 'order_cancel', 'order_partial_cancel', 'order_edit')
            )
            union all
            select 'order_edit'
            where exists (
                select 1
                from unnest(coalesce(r.role_powers, array[]::text[])) as legacy(power_key)
                where lower(legacy.power_key) in ('sales_dashboard', 'order_complete', 'order_cancel', 'order_partial_cancel')
            )
            union all
            select 'message_view'
            where exists (
                select 1
                from unnest(coalesce(r.role_powers, array[]::text[])) as legacy(power_key)
                where lower(legacy.power_key) in ('message_reply', 'message_delete', 'message_mark_answered', 'message_edit')
            )
            union all
            select 'message_edit'
            where exists (
                select 1
                from unnest(coalesce(r.role_powers, array[]::text[])) as legacy(power_key)
                where lower(legacy.power_key) in ('message_reply', 'message_delete', 'message_mark_answered')
            )
            union all
            select 'wallet_view'
            where exists (
                select 1
                from unnest(coalesce(r.role_powers, array[]::text[])) as legacy(power_key)
                where lower(legacy.power_key) in ('wallet_add_money', 'wallet_edit')
            )
            union all
            select 'wallet_edit'
            where exists (
                select 1
                from unnest(coalesce(r.role_powers, array[]::text[])) as legacy(power_key)
                where lower(legacy.power_key) = 'wallet_add_money'
            )
            union all
            select 'user_view'
            where exists (
                select 1
                from unnest(coalesce(r.role_powers, array[]::text[])) as legacy(power_key)
                where lower(legacy.power_key) in (
                    'user_add',
                    'user_bulk_add',
                    'user_bulk_additon',
                    'user_add_admin',
                    'user_add_billing_staff',
                    'user_add_custom_role',
                    'user_add_manager',
                    'user_add_sales_staff',
                    'user_edit',
                    'password_assist',
                    'default_password'
                )
            )
            union all
            select 'update_view'
            where exists (
                select 1
                from unnest(coalesce(r.role_powers, array[]::text[])) as legacy(power_key)
                where lower(legacy.power_key) in (
                    'site_control',
                    'about_edit',
                    'slider_manage',
                    'footer_manage',
                    'category_manage',
                    'loader_manage',
                    'site_logo_manage',
                    'update_edit'
                )
            )
            union all
            select 'update_edit'
            where exists (
                select 1
                from unnest(coalesce(r.role_powers, array[]::text[])) as legacy(power_key)
                where lower(legacy.power_key) in (
                    'site_control',
                    'about_edit',
                    'slider_manage',
                    'footer_manage',
                    'category_manage',
                    'loader_manage',
                    'site_logo_manage'
                )
            )
            union all
            select 'control_center_view'
            where exists (
                select 1
                from unnest(coalesce(r.role_powers, array[]::text[])) as legacy(power_key)
                where lower(legacy.power_key) in (
                    'req_power',
                    'approve_or_deny_power',
                    'approve_oe_deny_power',
                    'edit_roles_and_power',
                    'control_center_edit'
                )
            )
            union all
            select 'control_center_edit'
            where exists (
                select 1
                from unnest(coalesce(r.role_powers, array[]::text[])) as legacy(power_key)
                where lower(legacy.power_key) in (
                    'approve_or_deny_power',
                    'approve_oe_deny_power',
                    'edit_roles_and_power'
                )
            )
        ) merged
        where coalesce(power_key, '') <> ''
        order by power_key
    )
)
where role_powers is not null;

-- ---------------------------------------------------------------------------
-- 8) Reorder power keys by category and remap all stored references
-- ---------------------------------------------------------------------------

create temporary table tmp_power_key_map on commit drop as
with category_rank as (
    select *
    from (
        values
            ('Access Control', 1),
            ('Messages', 2),
            ('Orders And Sales', 3),
            ('Products', 4),
            ('Site Management', 5),
            ('Users And Passwords', 6),
            ('Wallet', 7),
            ('General', 8)
    ) as ranks(category_name, sort_order)
),
ordered as (
    select
        p.key as old_key,
        p.code,
        p.category,
        coalesce(cr.sort_order, 999) as category_sort_order,
        row_number() over (
            order by
                coalesce(cr.sort_order, 999),
                lower(coalesce(p.category, 'zzzz')),
                lower(coalesce(p.code, 'zzzz')),
                lower(coalesce(p.key, 'zzzz'))
        ) as new_position
    from public.powers p
    left join category_rank cr
      on lower(cr.category_name) = lower(coalesce(p.category, ''))
),
numbered as (
    select
        old_key,
        code,
        category,
        regexp_replace(old_key, '^.*?([0-9]+)$', '\1')::int as old_num,
        new_position as new_num,
        'Power' || lpad(new_position::text, 3, '0') as new_key
    from ordered
)
select *
from numbered;

update public.powers p
set key = 'TMP__' || m.new_key
from tmp_power_key_map m
where p.key = m.old_key
  and m.old_key <> m.new_key;

update public.powers p
set key = m.new_key
from tmp_power_key_map m
where p.key = 'TMP__' || m.new_key
  and m.old_key <> m.new_key;

update public.roles r
set role_powers = coalesce((
    select array_agg(mapped_key order by ordinality)
    from (
        select distinct on (mapped_key)
            ordinality,
            coalesce(m.new_key, item.power_key) as mapped_key
        from unnest(coalesce(r.role_powers, array[]::text[])) with ordinality as item(power_key, ordinality)
        left join tmp_power_key_map m
          on lower(m.old_key) = lower(item.power_key)
        where coalesce(item.power_key, '') <> ''
        order by mapped_key, ordinality
    ) deduped
), array[]::text[]);

update public.users u
set additional_Powers = (
    with parsed as (
        select case
            when u.additional_Powers is null or btrim(u.additional_Powers) = '' then '[]'::jsonb
            when u.additional_Powers ~ '^\s*\[' then u.additional_Powers::jsonb
            else to_jsonb(regexp_split_to_array(regexp_replace(u.additional_Powers, '[\[\]"'']', '', 'g'), '\s*,\s*'))
        end as arr
    ),
    remapped as (
        select jsonb_agg(
            case
                when lower(value) = lower(m.old_key) then to_jsonb(m.new_key)
                when lower(value) = lower('rm_power_' || m.old_num::text) then to_jsonb('rm_power_' || m.new_num::text)
                when lower(value) = lower('rm_power_' || m.old_key) then to_jsonb('rm_power_' || m.new_num::text)
                else to_jsonb(value)
            end
            order by ordinality
        ) as arr
        from parsed p
        left join lateral jsonb_array_elements_text(p.arr) with ordinality as entry(value, ordinality) on true
        left join tmp_power_key_map m
          on lower(entry.value) = lower(m.old_key)
          or lower(entry.value) = lower('rm_power_' || m.old_num::text)
          or lower(entry.value) = lower('rm_power_' || m.old_key)
    )
    select coalesce(arr, '[]'::jsonb)::text
    from remapped
)
where u.additional_Powers is not null;

alter table public.users
add column if not exists removed_role_powers jsonb not null default '[]'::jsonb;

update public.users u
set removed_role_powers = (
    select coalesce(jsonb_agg(coalesce(m.new_key, value) order by ordinality), '[]'::jsonb)
    from jsonb_array_elements_text(coalesce(u.removed_role_powers, '[]'::jsonb)) with ordinality as entry(value, ordinality)
    left join tmp_power_key_map m
      on lower(m.old_key) = lower(entry.value)
);

update public.access_requests ar
set requested_power_keys = (
    select coalesce(jsonb_agg(coalesce(m.new_key, value) order by ordinality), '[]'::jsonb)
    from jsonb_array_elements_text(coalesce(ar.requested_power_keys, '[]'::jsonb)) with ordinality as entry(value, ordinality)
    left join tmp_power_key_map m
      on lower(m.old_key) = lower(entry.value)
);

update public.access_audit_log al
set added_power_keys = (
    select coalesce(jsonb_agg(coalesce(m.new_key, value) order by ordinality), '[]'::jsonb)
    from jsonb_array_elements_text(coalesce(al.added_power_keys, '[]'::jsonb)) with ordinality as entry(value, ordinality)
    left join tmp_power_key_map m
      on lower(m.old_key) = lower(entry.value)
);

update public.access_audit_log al
set removed_power_keys = (
    select coalesce(jsonb_agg(coalesce(m.new_key, value) order by ordinality), '[]'::jsonb)
    from jsonb_array_elements_text(coalesce(al.removed_power_keys, '[]'::jsonb)) with ordinality as entry(value, ordinality)
    left join tmp_power_key_map m
      on lower(m.old_key) = lower(entry.value)
);

update public.access_audit_log al
set final_power_keys = (
    select coalesce(jsonb_agg(coalesce(m.new_key, value) order by ordinality), '[]'::jsonb)
    from jsonb_array_elements_text(coalesce(al.final_power_keys, '[]'::jsonb)) with ordinality as entry(value, ordinality)
    left join tmp_power_key_map m
      on lower(m.old_key) = lower(entry.value)
);

commit;
